### ISSUE TITLE
Optional .min suffix

### ISSUE THREAD

**Issue by ivanvermeyen** [GreanMaster/laravel-elixir-uglify#1]
Hi,

Thanks for this cool Elixir extension!
Any chance that you could make the `.min` suffix in the uglified filename optional?

Ivan

**Comment by panudetjt** [comment]
Thank for feedback Ivan :smile:

You just update lastest version from npm

and set `suffix` option to `false` like this

```
mix.uglify('**/*.js', 'public/js', {
    suffix: false
 });
```

hope this will help your issue 

Thank :bow:

**Comment by ivanvermeyen** [comment]
Thanks!  :)
