### ISSUE TITLE
Two return statements in extensions

### ISSUE THREAD

**Issue by mblarsen** [GreanMaster/laravel-elixir-uglify#3]
What is the intention of the two return statements—seems error prone?

https://github.com/GreanMaster/laravel-elixir-uglify/blob/master/index.js#L39-L48 

``` JavaScript
return gulp.src(src)
  .pipe(filter)
  .pipe(uglify(options)).on('error', onError)
  .pipe(gulpif(extConditon, rename({extname: '.min.js'})))
  .pipe(gulp.dest(output || config.jsOutput))
  .pipe(new Notification().message('Uglified!'));
});

return this.queueTask('uglify');
```

**Comment by panudetjt** [comment]
I have just rewrite my plugin to lastest Laravel Elixir, You should try it with lastest version.

Sorry for very late :'(

Hope you enjoy it :)
