### ISSUE TITLE
SyntaxError: Unexpected token >

### ISSUE THREAD

**Issue by cvcv01** [GreanMaster/laravel-elixir-uglify#4]
Laravel ver. 5.2.x 

I've installed: laravel-elixir-uglify

I've added the following code in gulpfile.js :

```
require('laravel-elixir-uglify');

elixir(function(mix) {
    mix.scripts('script.js', 'public/js/script.js');

    mix.uglify();
});
```

but get the error:

```
Elixir.extend('uglify', (src, output, options = {}) => {
                                                     ^
SyntaxError: Unexpected token >
```

Does laravel-elixir-uglify work with 5.2.x?

Thanks

**Comment by panudetjt** [comment]
What version of your node ?, I guess it may be 4 or under, Becuase that not
support the arrow function, Unfortunately.

**Comment by cvcv01** [comment]
node -v outputs v0.10.36

**Comment by panudetjt** [comment]
I'm so sorry, that too far for support, I can only recommend you to upgrade
to 5 or newer in this time.

**Comment by cvcv01** [comment]
Thanks for you help GreanMaster,

I've upgraded node.js to v6.7.0

Now I get this error:

```
  return new Elixir.GulpPaths()
         ^

TypeError: Elixir.GulpPaths is not a constructor
    at prepGulpPaths 
```

**Comment by panudetjt** [comment]
That's look weird, Because I'm tested on node.js v6.7.0 in windows 10, But don't have any error.

I've look on laravel document that I have got [script](https://laravel.com/docs/5.3/elixir#javascript).

I highly recommend use official plugin, I will deprecate this plugin soon.

Thank you very much for feedback @cvcv01.

👍

**Comment by cvcv01** [comment]
Ok thanks. Which official plugin do you mean?

**Comment by cvcv01** [comment]
Ok thanks!
